=== DigitalDataChainConsortium/vdi2770/vdi2770-processor/src/test/resources/vdi2770.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.vdi.de/schemas/vdi2770"
	targetNamespace="http://www.vdi.de/schemas/vdi2770"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	version="2019-08-23">
	<xs:annotation>
		<xs:appinfo>
			This XML schema declares the information model of
			the metadata file for
			VDI 2770
		</xs:appinfo>
	</xs:annotation>

	<xs:element name="Document">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DocumentId" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="DomainId" type="xs:string"
									use="required" />
								<xs:attribute name="IsPrimary" type="xs:boolean" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="DocumentIdDomain" maxOccurs="unbounded" />
				<xs:element ref="DocumentClassification"
					maxOccurs="unbounded" />
				<xs:element ref="ReferencedObject" maxOccurs="unbounded" />
				<xs:element ref="DocumentVersion" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="DocumentIdDomain">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Party">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Organization">
								<xs:complexType>
									<xs:attribute name="OrganizationId"
										type="xs:string" />
									<xs:attribute name="OrganizationName"
										type="xs:string" use="required" />
									<xs:attribute name="OrganizationOfficialName"
										type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Role" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Responsible" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="DocumentDomainId" type="xs:string"
				use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="DocumentClassification">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ClassId" type="xs:string" />
				<xs:element name="ClassName" minOccurs="0"
					maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="Language" type="xs:string"
									use="required" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="ClassificationSystem"
				type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="ReferencedObject">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ObjectId" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="ObjectType" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="Type" />
											<xs:enumeration value="Individual" />
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="RefType" type="xs:string" />
								<xs:attribute name="IsGloballyBiUnique"
									type="xs:boolean" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="ReferenceDesignation" type="xs:string"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="EquipmentId" type="xs:string"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="ProjectId" type="xs:string"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="Party" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Organization">
								<xs:complexType>
									<xs:attribute name="OrganizationId"
										type="xs:string" />
									<xs:attribute name="OrganizationName"
										type="xs:string" use="required" />
									<xs:attribute name="OrganizationOfficialName"
										type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Role" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Supplier" />
									<xs:enumeration value="Manufacturer" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="Description" minOccurs="0"
					maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="Language" type="xs:string"
									use="required" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="DocumentVersion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DocumentVersionId" />
				<xs:element ref="Language" maxOccurs="unbounded" />
				<xs:element name="Party" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Organization">
								<xs:complexType>
									<xs:attribute name="OrganizationId"
										type="xs:string" />
									<xs:attribute name="OrganizationName"
										type="xs:string" use="required" />
									<xs:attribute name="OrganizationOfficialName"
										type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Role" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Author" />
									<xs:enumeration value="Responsible" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element ref="DocumentDescription"
					maxOccurs="unbounded" />
				<xs:element ref="LifeCycleStatus" />
				<xs:element ref="DocumentRelationship" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element ref="DigitalFile" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="NumberOfPages"
				type="xs:positiveInteger" />
		</xs:complexType>
	</xs:element>

	<xs:element name="DocumentVersionId" type="xs:string" />

	<xs:element name="Language" type="xs:string" />

	<xs:element name="DocumentDescription">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Title" type="xs:string" />
				<xs:element name="SubTitle" type="xs:string"
					minOccurs="0" />
				<xs:element name="Summary" type="xs:string" />
				<xs:element name="KeyWords">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="KeyWord" type="xs:string"
								maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Language" type="xs:string"
				use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="LifeCycleStatus">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Party" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Organization">
								<xs:complexType>
									<xs:attribute name="OrganizationId"
										type="xs:string" />
									<xs:attribute name="OrganizationName"
										type="xs:string" use="required" />
									<xs:attribute name="OrganizationOfficialName"
										type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Role" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Responsible" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="Comments" minOccurs="0"
					maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="Language" type="xs:string"
									use="required" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="SetDate" type="xs:date" />
			<xs:attribute name="StatusValue" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="InReview" />
						<xs:enumeration value="Released" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="DocumentRelationship">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DocumentId">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="DomainId" type="xs:string"
									use="required" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="DocumentVersionId" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="Description" minOccurs="0"
					maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="Language" type="xs:string"
									use="required" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="RefersTo" />
						<xs:enumeration value="BasedOn" />
						<xs:enumeration value="Affecting" />
						<xs:enumeration value="TranslationOf" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="DigitalFile">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="FileFormat" type="xs:string"
						use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== DigitalDataChainConsortium/vdi2770/examples/folders/VDI2770_Main.xml
<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.vdi.de/schemas/vdi2770 ../vdi2770.xsd"
	xmlns="http://www.vdi.de/schemas/vdi2770">
	<DocumentId DomainId="INFAI" IsPrimary="true">INFAIH1.1</DocumentId>
	<DocumentIdDomain DocumentDomainId="INFAI">
		<Party Role="Responsible">
			<Organization OrganizationId="INFAI"
				OrganizationName="InfAI e.V."
				OrganizationOfficialName="Institut für Angewandte Informatik (InfAI) e. V." />
		</Party>
	</DocumentIdDomain>
	<DocumentClassification
		ClassificationSystem="VDI2770:2018">
		<ClassId>01-01</ClassId>
	</DocumentClassification>
	<ReferencedObject>
		<ObjectId ObjectType="Individual">I123</ObjectId>
		<ObjectId ObjectType="Type">ABC1223</ObjectId>
		<ObjectId ObjectType="Type">http://company-inc.com/4711</ObjectId>
		<Party Role="Manufacturer">
			<Organization OrganizationName="Company"
				OrganizationOfficialName="Company Inc." />
		</Party>
	</ReferencedObject>
	<DocumentVersion>
		<DocumentVersionId>2.0</DocumentVersionId>
		<Language>de</Language>
		<Party Role="Author">
			<Organization OrganizationId="INFAI"
				OrganizationName="InfAI e.V."
				OrganizationOfficialName="Institut für Angewandte Informatik (InfAI) e. V." />
		</Party>
		<DocumentDescription Language="de">
			<Title>Hauptdokument</Title>
			<Summary>Hauptdokument</Summary>
			<KeyWords>
				<KeyWord>Hauptdokument</KeyWord>
			</KeyWords>
		</DocumentDescription>
		<LifeCycleStatus StatusValue="Released"
			SetDate="2018-04-04">
			<Party Role="Responsible">
				<Organization OrganizationId="INFAI"
					OrganizationName="InfAI e.V."
					OrganizationOfficialName="Institut für Angewandte Informatik (InfAI) e. V." />
			</Party>
		</LifeCycleStatus>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="INFAI">456-29201</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="INFAI">AB393</DocumentId>
			<DocumentVersionId>2.0</DocumentVersionId>
		</DocumentRelationship>
		<DigitalFile FileFormat="application/pdf">VDI2770_Main.pdf</DigitalFile>
	</DocumentVersion>
</Document>

=== DigitalDataChainConsortium/vdi2770/examples/xml/Maindocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.vdi.de/schemas/vdi2770 vdi2770.xsd"
    xmlns="http://www.vdi.de/schemas/vdi2770">
	<DocumentId DomainId="BSP-OEM">XCP328490</DocumentId>
	<DocumentIdDomain DocumentDomainId="BSP-OEM">
		<Party Role="Responsible">
			<Organization OrganizationName="Beispiel GmbH"
                OrganizationOfficialName="Beispiel GmbH &amp; Co. KGaA" OrganizationId="BSP"/>
		</Party>
	</DocumentIdDomain>
	<DocumentClassification ClassificationSystem="VDI2770:2018">
		<ClassId>01-01</ClassId>
	</DocumentClassification>
	<ReferencedObject>
		<ObjectId RefType="product type" ObjectType="Type">BR-01</ObjectId>
		<Party Role="Manufacturer">
			<Organization OrganizationName="Beispiel GmbH"
                OrganizationOfficialName="Beispiel GmbH &amp; Co. KGaA"/>
		</Party>
		<Description Language="de">Baureihe</Description>
	</ReferencedObject>
	<ReferencedObject>
		<ObjectId RefType="product type" ObjectType="Type">BR-01-26</ObjectId>
		<Party Role="Manufacturer">
			<Organization OrganizationName="Beispiel GmbH"
                OrganizationOfficialName="Beispiel GmbH &amp; Co. KGaA"/>
		</Party>
		<Description Language="de">Modell</Description>
	</ReferencedObject>
	<ReferencedObject>
		<ObjectId RefType="serial number" ObjectType="Individual">XUJ-345-111</ObjectId>
		<Party Role="Manufacturer">
			<Organization OrganizationName="Beispiel GmbH"
                OrganizationOfficialName="Beispiel GmbH &amp; Co. KGaA"/>
		</Party>
		<Description Language="de">Seriennummer</Description>
	</ReferencedObject>
	<DocumentVersion>
		<DocumentVersionId>1.0</DocumentVersionId>
		<Language>de</Language>
		<Party Role="Author">
			<Organization OrganizationName="Beispiel GmbH"
                OrganizationOfficialName="Beispiel GmbH &amp; Co. KGaA" OrganizationId="BSP"/>
		</Party>
		<DocumentDescription Language="de">
			<Title>Hauptdokument</Title>
			<Summary>Das Hauptdoument ist eine Auflistung aller Dokumente einer Ebene.
                Gibt es zu dieser Ebene auch eine untergeordnete Ebene, so enthält die Auflistung auch die Hauptdokumente
                der zugehörigen ersten untergeordneten Ebene.
			</Summary>
			<KeyWords>
				<KeyWord>Hauptdokument</KeyWord>
				<KeyWord>Dokumentenliste</KeyWord>
			</KeyWords>
		</DocumentDescription>
		<LifeCycleStatus StatusValue="Released" SetDate="2018-04-04">
			<Party Role="Responsible">
				<Organization OrganizationName="Beispiel GmbH"
                    OrganizationOfficialName="Beispiel GmbH &amp; Co. KGaA" OrganizationId="BSP"/>
			</Party>
		</LifeCycleStatus>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">ts-dds-2234</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">ac345-339-112/07</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">ac345-339-112/02</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">ac345-339-112</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">ac345-339-112/00</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">ac345-339-112/00e</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">2016-04_FSA_24345</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">PTB-2016-3301-fsd-17</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">ba-dds-2234</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">as-44/02</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">iwp-dds-234/02/a</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">iwp-dds-234/02/p</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">ra-dds-234</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">e-dds-234/02</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">hub-dds-234</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">20180226-B-3229</DocumentId>
		</DocumentRelationship>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="BSP-OEM">g-dds-234</DocumentId>
		</DocumentRelationship>
		<DigitalFile FileFormat="application/pdf">VDI2770_Main.pdf</DigitalFile>
	</DocumentVersion>
</Document>

=== DigitalDataChainConsortium/vdi2770/examples/folders/456-29201/VDI2770_Metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.vdi.de/schemas/vdi2770 ../../vdi2770.xsd"
	xmlns="http://www.vdi.de/schemas/vdi2770">
	<DocumentId DomainId="INFAI">456-29201</DocumentId>
	<DocumentIdDomain DocumentDomainId="UL">
		<Party Role="Responsible">
			<Organization OrganizationId="UL"
				OrganizationName="Uni Leipzig"
				OrganizationOfficialName="Universität Leipzig" />
		</Party>
	</DocumentIdDomain>
	<DocumentClassification
		ClassificationSystem="VDI2770:2018">
		<ClassId>03-01</ClassId>
	</DocumentClassification>
	<ReferencedObject>
		<ObjectId ObjectType="Individual">I123</ObjectId>
		<ObjectId ObjectType="Type">ABC1223</ObjectId>
		<ObjectId ObjectType="Type">http://company-inc.com/4711</ObjectId>
		<Party Role="Manufacturer">
			<Organization OrganizationName="Company"
				OrganizationOfficialName="Company Inc." />
		</Party>
	</ReferencedObject>
	<DocumentVersion>
		<DocumentVersionId>2.0</DocumentVersionId>
		<Language>de</Language>
		<Language>en</Language>
		<Party Role="Author">
			<Organization OrganizationId="UL"
				OrganizationName="Uni Leipzig"
				OrganizationOfficialName="Universität Leipzig" />
		</Party>
		<DocumentDescription Language="de">
			<Title>Testtitel</Title>
			<Summary>Das ist ein kleiner Test</Summary>
			<KeyWords>
				<KeyWord>Test1</KeyWord>
				<KeyWord>Test2</KeyWord>
			</KeyWords>
		</DocumentDescription>
		<DocumentDescription Language="en">
			<Title>Test title</Title>
			<Summary>This is a test</Summary>
			<KeyWords>
				<KeyWord>Test1</KeyWord>
				<KeyWord>Test2</KeyWord>
			</KeyWords>
		</DocumentDescription>
		<LifeCycleStatus StatusValue="Released"
			SetDate="2018-04-04">
			<Party Role="Responsible">
				<Organization OrganizationId="UL"
					OrganizationName="Uni Leipzig"
					OrganizationOfficialName="Universität Leipzig" />
			</Party>
		</LifeCycleStatus>
		<DigitalFile FileFormat="application/pdf">demo.pdf</DigitalFile>
		<DigitalFile
			FileFormat="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">demo.xlsx</DigitalFile>
	</DocumentVersion>
</Document>

=== DigitalDataChainConsortium/vdi2770/examples/folders/AB393/VDI2770_Metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.vdi.de/schemas/vdi2770 ../../vdi2770.xsd"
	xmlns="http://www.vdi.de/schemas/vdi2770">
	<DocumentId DomainId="INFAI">AB393</DocumentId>
	<DocumentIdDomain DocumentDomainId="INFAI">
		<Party Role="Responsible">
			<Organization OrganizationId="INFAI"
				OrganizationName="InfAI e.V."
				OrganizationOfficialName="Institut für Angewandte Informatik (InfAI) e. V." />
		</Party>
	</DocumentIdDomain>
	<DocumentClassification
		ClassificationSystem="VDI2770:2018">
		<ClassId>02-01</ClassId>
	</DocumentClassification>
	<DocumentClassification
		ClassificationSystem="VDI2770:2018">
		<ClassId>01-01</ClassId>
	</DocumentClassification>
	<ReferencedObject>
		<ObjectId ObjectType="Type">P1.1</ObjectId>
		<ObjectId ObjectType="Individual">ABC1223</ObjectId>
		<ObjectId ObjectType="Type">http://company-inc.com/4711</ObjectId>
		<ObjectId ObjectType="Type">4711</ObjectId>
		<Party Role="Manufacturer">
			<Organization OrganizationName="Company"
				OrganizationOfficialName="Company Inc." />
		</Party>
	</ReferencedObject>
	<DocumentVersion>
		<DocumentVersionId>2.0</DocumentVersionId>
		<Language>de</Language>
		<Language>en</Language>
		<Party Role="Author">
			<Organization OrganizationId="INFAI"
				OrganizationName="InfAI e.V."
				OrganizationOfficialName="Institut für Angewandte Informatik (InfAI) e. V." />
		</Party>
		<DocumentDescription Language="de">
			<Title>Zweidokument</Title>
			<Summary>Noch ein Dokument</Summary>
			<KeyWords>
				<KeyWord>2</KeyWord>
				<KeyWord>zwei</KeyWord>
			</KeyWords>
		</DocumentDescription>
		<DocumentDescription Language="en">
			<Title>Foo</Title>
			<Summary>Test</Summary>
			<KeyWords>
				<KeyWord>Bar</KeyWord>
			</KeyWords>
		</DocumentDescription>
		<LifeCycleStatus StatusValue="Released"
			SetDate="2018-04-04">
			<Party Role="Responsible">
				<Organization OrganizationId="INFAI"
					OrganizationName="InfAI e.V."
					OrganizationOfficialName="Institut für Angewandte Informatik (InfAI) e. V." />
			</Party>
		</LifeCycleStatus>
		<DigitalFile FileFormat="application/pdf">demo.pdf</DigitalFile>
		<DigitalFile
			FileFormat="application/vnd.openxmlformats-officedocument.wordprocessingml.document">demo.docx</DigitalFile>
	</DocumentVersion>
</Document>

=== DigitalDataChainConsortium/vdi2770/examples/xml/validation.xml
<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns="http://www.vdi.de/schemas/vdi2770"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.vdi.de/schemas/vdi2770 vdi2770.xsd">
	<DocumentId DomainId="DemoDomain" IsPrimary="true">4711Demo</DocumentId>
	<DocumentId DomainId="MyDomain" IsPrimary="false">AB-8889-XY/40</DocumentId>
	<DocumentIdDomain DocumentDomainId="DemoDomain">
		<Party Role="Responsible">
			<Organization OrganizationId="ULE"
				OrganizationName="Uni Leipzig"
				OrganizationOfficialName="Universität Leipzig" />
		</Party>
	</DocumentIdDomain>
	<DocumentIdDomain DocumentDomainId="MyDomain">
		<Party Role="Responsible">
			<Organization OrganizationId="CUS"
				OrganizationName="Customer" OrganizationOfficialName="Customer GmbH" />
		</Party>
	</DocumentIdDomain>
	<DocumentClassification
		ClassificationSystem="VDI2770:2018">
		<ClassId>03-01</ClassId>
		<ClassName Language="de">Montage, Inbetriebnahme, Demontage</ClassName>
		<ClassName Language="en">assembly, disassembly</ClassName>
	</DocumentClassification>
	<DocumentClassification
		ClassificationSystem="IEC61355">
		<ClassId>DD</ClassId>
		<ClassName Language="de">Technische Berichte</ClassName>
		<ClassName Language="en">Technical reports</ClassName>
	</DocumentClassification>
	<ReferencedObject>
		<ObjectId ObjectType="Individual" RefType="serial number">29389-2139292</ObjectId>
		<ObjectId ObjectType="Type" RefType="product type">4023/A</ObjectId>
		<ReferenceDesignation>#ABC 001</ReferenceDesignation>
		<ReferenceDesignation>#ABC 001 .99</ReferenceDesignation>
		<EquipmentId>900.330.30/100</EquipmentId>
		<ProjectId>P001</ProjectId>
		<Party Role="Manufacturer">
			<Organization OrganizationId="ULE"
				OrganizationName="Uni Leipzig"
				OrganizationOfficialName="Universität Leipzig" />
		</Party>
		<Party Role="Supplier">
			<Organization OrganizationId="ACME"
				OrganizationName="ACME" OrganizationOfficialName="ACME INC" />
		</Party>
		<Description Language="en">Product A</Description>
		<Description Language="de">Produkt A</Description>
	</ReferencedObject>
	<DocumentVersion NumberOfPages="100">
		<DocumentVersionId>1.0</DocumentVersionId>
		<Language>de</Language>
		<Language>en</Language>
		<Party Role="Author">
			<Organization OrganizationId="ULE"
				OrganizationName="Uni Leipzig"
				OrganizationOfficialName="Universität Leipzig" />
		</Party>
		<DocumentDescription Language="de">
			<Title>Demo Bericht</Title>
			<SubTitle>Ein kleines Beispiel für einen Untertitel</SubTitle>
			<Summary>Dies ist eine Zusammenfassung in deutsch für den beispielhaften Demo Bericht</Summary>
			<KeyWords>
				<KeyWord>Test</KeyWord>
				<KeyWord>Demo</KeyWord>
			</KeyWords>
		</DocumentDescription>
		<DocumentDescription Language="en">
			<Title>Demo Report</Title>
			<SubTitle>A short example for sub titles</SubTitle>
			<Summary>This is a summary in english for the Demo Report document</Summary>
			<KeyWords>
				<KeyWord>Test</KeyWord>
				<KeyWord>Demo</KeyWord>
			</KeyWords>
		</DocumentDescription>
		<LifeCycleStatus SetDate="2019-05-07"
			StatusValue="Released">
			<Party Role="Responsible">
				<Organization OrganizationId="ULE"
					OrganizationName="Uni Leipzig"
					OrganizationOfficialName="Universität Leipzig" />
			</Party>
			<Comments Language="de">Die Version ist frei erfunden, aber freigegeben.</Comments>
			<Comments Language="en">This milestone is just for testing purposes</Comments>
		</LifeCycleStatus>
		<DocumentRelationship Type="RefersTo">
			<DocumentId DomainId="DemoDomain">449890</DocumentId>
			<Description Language="de">Dies ist eine Dokumentenbeziehung, die ausschließlich auf eine Dokument ID verweist.</Description>
			<Description Language="en">This is a document relationship, that only refers to a document id.</Description>
		</DocumentRelationship>
		<DocumentRelationship Type="Affecting">
			<DocumentId DomainId="MyDomain">9994/22029</DocumentId>
			<DocumentVersionId>1.0</DocumentVersionId>
			<DocumentVersionId>2.0</DocumentVersionId>
			<Description Language="de">Diese Beziehung gilt für genau zwei Dokumentversion eines Dokumentes.</Description>
		</DocumentRelationship>
		<DigitalFile FileFormat="application/pdf">test.pdf</DigitalFile>
		<DigitalFile FileFormat="application/vnd.ms-excel">test.xls</DigitalFile>
	</DocumentVersion>
</Document>
